config/routes.rb
#
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, except: [:index] do

    resources :doses, only: [:new, :create, :destroy]

  end
  resources :doses, only: [ :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy

    redirect_to root_path
  end



  private

  def cocktail_params
      params.require(:cocktail).permit(:name, :dose, :ingredient, :photo)
  end


end

app/controllers/doses_controller.rb
class DosesController < ApplicationController


  def new
    @ingredients = Ingredient.all
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy

    redirect_to root_path
  end

  private

  def dose_params
      params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/3323682/pexels-photo-3323682.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260);">
    <h1>Welcome to <strong>Mr Cocktail</strong></h1>
    <p> Get shitfaced and more</p>
    <p> <%= link_to "Add a cocktail", new_cocktail_path, class: 'btn btn-primary'%></p>
</div>

<div class="headline">
  <h3>All cocktails:</h3>
</div>

<div class="container">

  <div class="row">

    <% @cocktails.each do |cocktail| %>
      <div class="col-sm-6">
        <% if cocktail.photo.attached? %>

          <div class="cocktail-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key %>');">
            <h4> <%= cocktail.name%> <%= link_to "Edit", cocktail_path(cocktail), method: :get, class: 'btn-sm btn-primary'%> </h4>
            <h4>_________________ </h4>
            <p><strong>Recipe:</strong></p>
            <% cocktail.doses.each do |d| %>
              <p> -> <%= d.ingredient.name %> ~ <%= d.description %> </p>
            <% end %>
            <%= link_to 'Delete', cocktail, method: :delete, class: 'btn-sm btn-danger' %>
          </div>

        <% else %>

          <div class="cocktail-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://source.unsplash.com/random);">
            <h4><strong>Cocktail:</strong> </h4>
            <h4> <%= cocktail.name%> <%= link_to "Edit", cocktail_path(cocktail), method: :get, class: 'btn-sm btn-primary'%> </h4>
            <h4>_________________ </h4>
            <p><strong>Recipe:</strong></p>
            <% cocktail.doses.each do |d| %>
              <p> -> <%= d.ingredient.name %> ~ <%= d.description %> </p>
            <% end %>
            <%= link_to 'Delete', cocktail, method: :delete, class: 'btn-sm btn-danger' %>
          </div>

        <% end %>


      </div>
    <% end %>

   </div>
</div>

app/views/cocktails/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/3323682/pexels-photo-3323682.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260);">
    <h1>Create your own Cocktail!</h1>
    <br>
    <p> <%= link_to "Add a cocktail", new_cocktail_path, class: 'btn btn-primary'%></p>
</div>

<div class="headline">
  <%= link_to "Back", root_path, class: "btn-sm btn-primary" %>
  <br>
  <h3>Add the name:</h3>
</div>

<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit%>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/3323682/pexels-photo-3323682.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260);">
  <h1><%= @cocktail.name %></h1>
  <br>
  <p> <%= link_to "Add dose", new_cocktail_dose_path(@cocktail), class: 'btn btn-primary'%></p>
</div>

<div class="headline">
  <%= link_to "Back", root_path, class: "btn-sm btn-primary" %>
  <br>
  <h3>Here is the cocktail:</h3>
</div>

<div class="container">

  <div class="row">
    <div class="col-sm">

      <div class="cocktail">
        <p><strong>Cocktail:</strong> <%= @cocktail.name %> </p>
        <p> <%= cl_image_tag "v1ycblybxauumc7dwwk5wgupp2ix", height: 300, width: 400, crop: :fill %></p>
        <p><strong>Recipe:</strong></p>
        <% @cocktail.doses.each do |d| %>
          <p> -> <%= d.ingredient.name %> ~ <em>Amount:</em> <%= d.description %> <%= link_to 'Delete', d, method: :delete, class: 'btn-sm btn-danger' %> </p>
        <% end %>
      </div>

    </div>
  </div>

</div>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient, collection: @ingredients %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>